import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClientProvider } from "@/components/core";
import { UserProvider } from "@/components/context/UserContext";

const googlesanse = localFont({
  src: [
    { path: "../public/fonts/google-sans/ProductSans-Thin.ttf", weight: "100" },
    { path: "../public/fonts/google-sans/ProductSans-Light.ttf", weight: "200" },
    { path: "../public/fonts/google-sans/ProductSans-Regular.ttf", weight: "300" },
    { path: "../public/fonts/google-sans/ProductSans-Medium.ttf", weight: "400" },
    { path: "../public/fonts/google-sans/ProductSans-Bold.ttf", weight: "600" },
  ],
  variable: "--googlesanse",
});

export const metadata: Metadata = {
  title: "Skilline.ai || Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={cn(googlesanse.className)}>
        <ClientProvider>
          <main>
          <UserProvider>
            {children}
            </UserProvider>
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
